#! /usr/bin/env bash
#renaming filess

#find . -type f -name '*.dcm' -exec rename -n 's/b.dcm$/B/' {} \;
#find . -type f ! -name "myscript" -exec rename -v 'y/[a-z]/[A-Z]/' {} \;
#find . -type d -depth -exec rename -n 'y/[a-z]/[A-Z]/' {} \;


#now to drop off the extra zeros to restrict file name to 8 chars



#find . -type f ! -name "myscript" -exec rename -v 's/_0000B$//' {} \;

